version: 16
jobs:
- name: Build & Publish
  steps:
  - !CheckoutStep
    name: Checkout
    cloneCredential: !DefaultCredential {}
    withLfs: false
    withSubmodules: false
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !CommandStep
    name: Build & Publish Docker Image
    runInContainer: true
    image: docker:20.10.16-alpine3.16
    interpreter: !DefaultInterpreter
      commands:
      - set -e
      - ''
      - docker build -t ccr.ccs.tencentyun.com/ameow_projects/notification-gateway-lite:v0.0.@build_number@
        .
      - docker login -u @secret:registry_username@ -p @secret:registry_password@ ccr.ccs.tencentyun.com
      - docker push ccr.ccs.tencentyun.com/ameow_projects/notification-gateway-lite:v0.0.@build_number@
      - ''
      - docker login -u @secret:aliyun_registry_username@ -p @secret:aliyun_registry_password@
        registry.cn-shenzhen.aliyuncs.com
      - docker tag ccr.ccs.tencentyun.com/ameow_projects/notification-gateway-lite:v0.0.@build_number@
        registry.cn-shenzhen.aliyuncs.com/ameow_projects/notification-gateway-lite:v0.0.@build_number@
      - docker push registry.cn-shenzhen.aliyuncs.com/ameow_projects/notification-gateway-lite:v0.0.@build_number@
      - ''
      - docker login -u cn-south-1@@@secret:huawei_ak@ -p @secret:huawei_secret@ swr.cn-south-1.myhuaweicloud.com
      - docker tag ccr.ccs.tencentyun.com/ameow_projects/notification-gateway-lite:v0.0.@build_number@ swr.cn-south-1.myhuaweicloud.com/ameow/notification-gateway-lite:v0.0.@build_number@
      - docker push swr.cn-south-1.myhuaweicloud.com/ameow/notification-gateway-lite:v0.0.@build_number@
    useTTY: false
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !PushRepository
    name: Sync with GitHub
    remoteUrl: https://github.com/LeslieLeung/notification-gateway-lite.git
    userName: LeslieLeung
    passwordSecret: github_access_token
    withLfs: false
    force: true
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  triggers:
  - !BranchUpdateTrigger
    branches: main
  retryCondition: '"Log" contains "failed"'
  maxRetries: 3
  retryDelay: 30
  cpuRequirement: 250
  memoryRequirement: 256
  timeout: 3600
